### ISSUE TITLE
Vanced Manager crash at startup

### ISSUE THREAD

**Issue by ArmynC** [YTVanced/VancedManager#105]
**I've managed to solve it, for now. I don't exactly know which was the cause. Check below for details.**

**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Samsung Galaxy S10
- Operating System: Android
- Android Version: 9
- Vanced Manager Version: 1.10 (Big Sur)

**Please describe the problem you are having in as much detail as possible:**

_Vanced Manager keeps stopping_ when I start it

**Steps to reproduce:**
1. Download
2. Install
3. Try to open it

**Further details:**
Magisk 20.4
Lucky Patcher Toolbox used

> [08-04 15:15:40.150 30563:30563 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.vanced.manager, PID: 30563
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vanced.manager/com.vanced.manager.ui.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3113)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3256)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7037)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at b.b.k.m.y(:11)
	at b.b.k.m.l(Unknown Source:0)
	at b.b.k.s.setContentView(Unknown Source:4)
	at b.b.k.i.onCreate(:2)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:550)
	at android.app.Dialog.show(Dialog.java:391)
	at a.a.a.d.a.onCreate(:6)
	at com.vanced.manager.ui.MainActivity.onCreate(Unknown Source:3)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3093)
	... 11 more

**Comment by ChrisBGL** [comment]
Same Problem, same conditions here with Samsung Galaxy Tab S5e. No solution.

**Comment by X1nto** [comment]
We probably already fixed this, wait for new release which will be available soon™

**Comment by X1nto** [comment]
@ArmynC @ChrisBGL check the new 1.2.0 release. All crashes should be fixed

**Comment by petrolhead77** [comment]
Phone Specifications:

Brand: Pixel 4 XL
Operating System: Android
Android Version: 11 Beta 3
Vanced Manager Version: 1.10 (Big Sur) (works, but not v 1.20)

**Comment by X1nto** [comment]
> Phone Specifications:
> 
> Brand: Pixel 4 XL
> Operating System: Android
> Android Version: 11 Beta 3
> Vanced Manager Version: 1.10 (Big Sur) (works, but not v 1.20)

Open a new issue and send a logcat

**Comment by ChrisBGL** [comment]
> @ArmynC @ChrisBGL check the new 1.2.0 release. All crashes should be fixed

Works! Thank you.
