### ISSUE TITLE
Installation not possible

### ISSUE THREAD

**Issue by oxk4r01** [YTVanced/VancedManager#183]
Not possible install MicroG, nor YouTube, nor YouTube Music. Unable to update or nothing. Suddenly everything stopped working.
Samsung Galaxy Tab S4.

**Comment by rajarshiamity** [comment]
Yes. Same with me. Not able to download any of the three files. Nokia 6.1

**Comment by fawazahmed0** [comment]
Same here

**Comment by Imerimer** [comment]
Same issue on nexus 6p with lineageOS. Vanced manager force close after all apks are downloaded (root mode).
Logcat output (filtered on "vanced" string):

`[10-12 08:57:01.425 8605:8605 D/su]
Checking whether app [uid:10114, pkgName: com.vanced.manager] is allowed to be root

[10-12 08:57:38.474 7129:7129 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.vanced.manager, PID: 7129
java.lang.RuntimeException: java.io.IOException: write failed: EPIPE (Broken pipe)
	at e.a.a.h.h.e(:16)
	at e.a.a.h.g.a(:18)
	at e.a.a.d.a.c.a(:24)
	at e.a.a.d.a.c$a$d.a(:32)
	at e.e.n.b.run(:2)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.io.IOException: write failed: EPIPE (Broken pipe)
	at libcore.io.IoBridge.write(IoBridge.java:558)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at e.h.a.c.g.O(:1)
	... 12 more
Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
	at libcore.io.Linux.writeBytes(Native Method)
	at libcore.io.Linux.write(Linux.java:288)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:345)
	at libcore.io.IoBridge.write(IoBridge.java:553)
	... 15 more

[10-12 08:57:39.241 822:909 I/ActivityManager]
Showing crash dialog for package com.vanced.manager u0

[10-12 08:57:40.941 822:27482 W/ActivityManager]
  Force finishing activity com.vanced.manager/.ui.MainActivity

[10-12 08:57:40.999 822:27482 I/ActivityManager]
Killing 7129:com.vanced.manager/u0a114 (adj 0): crash

[10-12 08:57:41.068 8605:8605 D/su]
Finishing su operation for app [uid:10114, pkgName: com.vanced.manager]

[10-12 08:57:58.178 822:822 W/JobServiceContext]
Time-out while trying to bind df5affe #u0a114/1734160625 com.vanced.manager/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService, dropping.`

**Comment by X1nto** [comment]
> Same issue on nexus 6p with lineageOS. Vanced manager force close after all apks are downloaded (root mode).
> Logcat output (filtered on "vanced" string):
> 
> `[10-12 08:57:01.425 8605:8605 D/su]
> Checking whether app [uid:10114, pkgName: com.vanced.manager] is allowed to be root
> 
> [10-12 08:57:38.474 7129:7129 E/AndroidRuntime]
> FATAL EXCEPTION: main
> Process: com.vanced.manager, PID: 7129
> java.lang.RuntimeException: java.io.IOException: write failed: EPIPE (Broken pipe)
> at e.a.a.h.h.e(:16)
> at e.a.a.h.g.a(:18)
> at e.a.a.d.a.c.a(:24)
> at e.a.a.d.a.c$a$d.a(:32)
> at e.e.n.b.run(:2)
> at android.os.Handler.handleCallback(Handler.java:790)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:164)
> at android.app.ActivityThread.main(ActivityThread.java:6494)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> Caused by: java.io.IOException: write failed: EPIPE (Broken pipe)
> at libcore.io.IoBridge.write(IoBridge.java:558)
> at java.io.FileOutputStream.write(FileOutputStream.java:326)
> at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
> at e.h.a.c.g.O(:1)
> ... 12 more
> Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
> at libcore.io.Linux.writeBytes(Native Method)
> at libcore.io.Linux.write(Linux.java:288)
> at libcore.io.BlockGuardOs.write(BlockGuardOs.java:345)
> at libcore.io.IoBridge.write(IoBridge.java:553)
> ... 15 more
> 
> [10-12 08:57:39.241 822:909 I/ActivityManager]
> Showing crash dialog for package com.vanced.manager u0
> 
> [10-12 08:57:40.941 822:27482 W/ActivityManager]
> Force finishing activity com.vanced.manager/.ui.MainActivity
> 
> [10-12 08:57:40.999 822:27482 I/ActivityManager]
> Killing 7129:com.vanced.manager/u0a114 (adj 0): crash
> 
> [10-12 08:57:41.068 8605:8605 D/su]
> Finishing su operation for app [uid:10114, pkgName: com.vanced.manager]
> 
> [10-12 08:57:58.178 822:822 W/JobServiceContext]
> Time-out while trying to bind df5affe #u0a114/1734160625 com.vanced.manager/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService, dropping.`

Are you using LineageSU by any chance?

**Comment by Imerimer** [comment]
Yes, the default SU !

Rémi Saunier

________________________________

**Comment by X1nto** [comment]
> Yes, the default SU ! 
Only Magisk is supported, other SU solutions have problems
