### ISSUE TITLE
App crashes on clicking install microG

### ISSUE THREAD

**Issue by anjanik012** [YTVanced/VancedManager#353]
**Phone Specifications:**
- Brand: Xiaomi
- Operating System: crDroid 7.2
- Android Version: 11
- Vanced Manager Version: 2.1.0

**Please describe the problem you are having in as much detail as possible:**
App crashes on clicking install microG. Also it fails to fetch latest version info.
![Screenshot_20210114-220239_Vanced_Manager~3](https://user-images.githubusercontent.com/24349858/104620147-af4b9400-56b4-11eb-8e20-20e25b7f3eb5.png)

**Steps to reproduce:**

- Open non root mode
- Click install microG

**Further details:**

Log after clicking install microG
```
2021-01-14 22:08:58.377 28873-28971/com.vanced.manager E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-10
    Process: com.vanced.manager, PID: 28873
    java.net.MalformedURLException: no protocol: 
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at com.github.kittinunf.fuel.core.Encoding.createUrl(Encoding.kt:37)
        at com.github.kittinunf.fuel.core.Encoding.access$createUrl(Encoding.kt:9)
        at com.github.kittinunf.fuel.core.Encoding$encoder$1.invoke(Encoding.kt:19)
        at com.github.kittinunf.fuel.core.Encoding$encoder$1.invoke(Encoding.kt:9)
        at com.github.kittinunf.fuel.core.Encoding$request$2.invoke(Encoding.kt:25)
        at com.github.kittinunf.fuel.core.Encoding$request$2.invoke(Encoding.kt:9)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.github.kittinunf.fuel.core.Encoding.getRequest(Unknown Source:2)
        at com.github.kittinunf.fuel.core.FuelManager.download(FuelManager.kt:129)
        at com.github.kittinunf.fuel.Fuel.download(Unknown Source:12)
        at com.github.kittinunf.fuel.core.RequestFactory$Convenience$DefaultImpls.download$default(RequestFactory.kt:68)
        at com.vanced.manager.utils.DownloadHelper$fuelDownload$1.invokeSuspend(DownloadHelper.kt:23)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

I also found that `url` in `DownloadHelper.kt:23` is actually empty causing `MalformedURLException`

**Comment by X1nto** [comment]
try clearing data of manager

**Comment by anjanik012** [comment]
> try clearing data of manager

I built from `dev`. Tried clearing data as well. Still crashing.

**Comment by X1nto** [comment]
> > try clearing data of manager
> 
> I built from `dev`. Tried clearing data as well. Still crashing.

works fine for me, do you have any firewalls or DNS active? they might be blocking connection to vancedapp.com

**Comment by anjanik012** [comment]
I'm sorry, something is wrong with my network :(

**Comment by X1nto** [comment]
Thanks for reporting btw, I've made a commit which will prevent crashes if something like that occurs: f9c174dbf9d1bacc083600ccfe55d00c10f29972
