### ISSUE TITLE
continously crashing MIUI

### ISSUE THREAD

**Issue by tiziodcaio** [YTVanced/VancedManager#368]
**Phone Specifications:**
- Brand: Xiaomi
- Operating System: MIUI 12.0.3 EU (miui opt. Disabled)
- Android Version: 10
- Vanced Manager Version: 2.2.0

**Please describe the problem you are having in as much detail as possible:**
Crash

**Steps to reproduce:**
Open the app

**Further details:**
java.lang.IllegalArgumentException: baseUrl must end in /: https://github.com/YTVanced/VancedManager
	at b0.b0$b.a(:3)
	at s.a.a.h.c.a(:20)
	at s.a.a.h.c.b(Unknown Source:25)
	at s.a.a.a.a.f0.H0(:12)
	at s.a.a.e.b.a.b.O(Unknown Source:11)
	at androidx.fragment.app.Fragment.j0(Unknown Source:15)
	at w.m.b.r.U(:29)
	at w.m.b.r.S(:1)
	at w.m.b.r.T(Unknown Source:47)
	at w.m.b.a.h(:2)
	at w.m.b.r.D(:7)
	at w.m.b.r.Z(Unknown Source:84)
	at w.m.b.r.B(:4)
	at w.m.b.r$d.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by KevinX8** [comment]
Update to 2.2.1 manually thanks
