### ISSUE TITLE
Interact_across_users permission

### ISSUE THREAD

**Issue by thedansu** [YTVanced/VancedManager#436]
Getting this error when trying install microg. This error occurs on a non-admin user. The admin account on the same tablet was able to install without issue. galaxy S7+ on Android 11.

VMNetTools: Fetching using URL: https://vancedapp.com/api/v1
VMInstall: java.lang.SecurityException: You need INTERACT_ACROSS_USERS or MANAGE_USERS permission to: check getUserRestrictions
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
	at android.os.Parcel.createException(Parcel.java:2369)
	at android.os.Parcel.readException(Parcel.java:2352)
	at android.os.Parcel.readException(Parcel.java:2294)
	at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:474)
	at android.content.pm.PackageInstaller.createSession(PackageInstaller.java:440)
	at d.a.a.h.h.d(Unknown Source:47)
	at i.onClick(java-style lambda group:12)
	at android.view.View.performClick(View.java:8160)
	at android.widget.TextView.performClick(TextView.java:16127)
	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:3)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.UserManagerService.checkManageOrInteractPermissionIfCallerInOtherProfileGroup(UserManagerService.java:1688)
	at com.android.server.pm.UserManagerService.getUserRestrictions(UserManagerService.java:2238)
	at com.android.server.pm.PackageManagerService.isUserRestricted(PackageManagerService.java:15593)
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:593)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:563)

**Comment by X1nto** [comment]
Obviously you won't be able to install apps on a regular user account

**Comment by thedansu** [comment]
Well I was able to install vanced manager along with myriad apps from play store with that user so isn't it reasonable to expect to be able to install microg and yt vanced?

**Comment by X1nto** [comment]
> Well I was able to install vanced manager along with myriad apps from play store with that user so isn't it reasonable to expect to be able to install microg and yt vanced?

Installing from google play and file explorer will work because both of them are system apps

**Comment by ezra100** [comment]
Hi
Please notice you can still install it via ADB [as explained here](https://telegra.ph/Installation-for-Vanced-09-01#NON-Root-v15-and-above), you'd just have to add `--user <uid>` to the adb command.
(So if the UID of the secondary user is 11 you'd run `adb install-multiple --user 11 YouTube_XX XX.XX_API21nodpivBlack-vX.X.X-vanced.apk split_config.arm64_v8a.apk split_config.en.apk`)

To get the user's UID run `adb shell pm list users`
The output would be something like:
```
Users:
	UserInfo{0:Ezra:c13} running
	UserInfo{11:Jake:410} running
	UserInfo{12:Test:410} running

```
So if Jake is the user you want to install to, the UID is 11.

**Comment by ezra100** [comment]
Btw, you can also download the apks for the Music ang MicroG apps and install them via file explorer.
As for the YouTube app - it wouldn't work since its apk is split, but you can merge the splits into one apk [as described here](https://apk4all.com/android/how-to-combine-split-apks-into-one/) and then install the merged apk.

And of course, if your device is rooted you can also install the root version on the admin user and it would be installed for all users.
