### ISSUE TITLE
microG installation failing on devicewith multiple users

### ISSUE THREAD

**Issue by sumit0k** [YTVanced/VancedManager#522]
Hi there,
I am getting following error on installing microG.

```
Advanced

java.lang.SecurityException: You need INTERACT_ACROSS_USERS or MANAGE_USERS permission to: check getUser Restrictions

at android.os.Parcel.createExceptionOrNull(Parcel.java:2385) at android.os.Parcel.createException (Parcel.java:2369) at android.os.Parcel.readException (Parcel.java:2352)

at android.os.Parcel.readException(Parcel.java:2294)

at android.content.pm.lPackageinstaller$Stub$Proxy.createSession(IPa ckageinstaller.java:474)

at

android.content.pm.Packageinstaller.createSession(Package Installer.

java:440)

at d.a.a.h.h.d(Unknown Source:47)

at i.onClick(java-style lambda group:12) at android.view.View.performClick(View.java:8160) at android.widget.TextView.performClick(TextView.java:16220)

at com.google.android.material.button.Material Button.performClick(Unk nown Source:3)

at android.view.View.performClickInternal(View.java:8137)

at android.view.View.access $3700(View.java:888) at android.view.View$PerformClick.run(View.java:30236) at android.os.Handler.handleCallback(Handler.java:938)

at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:246)

at android.app.ActivityThread.main(ActivityThread.java:8512) at java.lang.reflect.Method.invoke(Native Method) at

com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Runti melnit.java:596)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

CLOSE
```

**Comment by X1nto** [comment]
You need to be in the admin account in order to install apps from 3rd party installers
